/* ============================================
   Realistic mock data for the complaint portal
   ============================================ */

// --- Mock Users ---
export const mockUsers = {
  student: {
    id: 'STU-2024-001',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@abes.ac.in',
    phone: '9876543210',
    role: 'student',
    avatar: null,
    department: 'Computer Science & Engineering',
    departmentId: 'cse',
    branch: 'CSE',
    year: '3rd Year',
    rollNumber: '2100910310042',
    section: 'A',
    enrollmentYear: 2021,
    createdAt: '2024-08-15T10:00:00Z',
  },
  faculty: {
    id: 'FAC-2024-001',
    name: 'Dr. Priya Sharma',
    email: 'priya.sharma@abes.ac.in',
    phone: '9876543211',
    role: 'faculty',
    avatar: null,
    department: 'Computer Science & Engineering',
    departmentId: 'cse',
    designation: 'Associate Professor',
    employeeId: 'EMP-CSE-042',
    createdAt: '2020-06-01T10:00:00Z',
  },
  coordinator: {
    id: 'COD-2024-001',
    name: 'Dr. Rajesh Kumar',
    email: 'rajesh.kumar@abes.ac.in',
    phone: '9876543212',
    role: 'coordinator',
    avatar: null,
    department: 'Electronics & Communication',
    departmentId: 'ece',
    designation: 'Professor & HOD',
    employeeId: 'EMP-ECE-001',
    createdAt: '2018-07-15T10:00:00Z',
  },
  admin: {
    id: 'ADM-2024-001',
    name: 'Mr. Ravi Tiwari',
    email: 'admin@abes.ac.in',
    phone: '9876543213',
    role: 'admin',
    avatar: null,
    department: 'Administration',
    departmentId: 'admin_dept',
    designation: 'System Administrator',
    employeeId: 'EMP-ADM-001',
    createdAt: '2019-01-01T10:00:00Z',
  },
};

// --- Mock Students List (for admin) ---
export const mockStudentsList = [
  { id: 'STU-2024-001', name: 'Arjun Mehta', email: 'arjun.mehta@abes.ac.in', department: 'CSE', year: '3rd Year', status: 'active' },
  { id: 'STU-2024-002', name: 'Priya Gupta', email: 'priya.gupta@abes.ac.in', department: 'ECE', year: '2nd Year', status: 'active' },
  { id: 'STU-2024-003', name: 'Rahul Verma', email: 'rahul.verma@abes.ac.in', department: 'ME', year: '4th Year', status: 'active' },
  { id: 'STU-2024-004', name: 'Sneha Agarwal', email: 'sneha.agarwal@abes.ac.in', department: 'CSE', year: '1st Year', status: 'active' },
  { id: 'STU-2024-005', name: 'Vikas Yadav', email: 'vikas.yadav@abes.ac.in', department: 'IT', year: '3rd Year', status: 'active' },
  { id: 'STU-2024-006', name: 'Ananya Singh', email: 'ananya.singh@abes.ac.in', department: 'EE', year: '2nd Year', status: 'inactive' },
  { id: 'STU-2024-007', name: 'Karan Sharma', email: 'karan.sharma@abes.ac.in', department: 'CE', year: '4th Year', status: 'active' },
  { id: 'STU-2024-008', name: 'Megha Joshi', email: 'megha.joshi@abes.ac.in', department: 'MBA', year: '1st Year', status: 'active' },
  { id: 'STU-2024-009', name: 'Rohan Patel', email: 'rohan.patel@abes.ac.in', department: 'CSE', year: '3rd Year', status: 'active' },
  { id: 'STU-2024-010', name: 'Ishita Kapoor', email: 'ishita.kapoor@abes.ac.in', department: 'MCA', year: '2nd Year', status: 'active' },
  { id: 'STU-2024-011', name: 'Amit Rawat', email: 'amit.rawat@abes.ac.in', department: 'ECE', year: '3rd Year', status: 'active' },
  { id: 'STU-2024-012', name: 'Divya Nair', email: 'divya.nair@abes.ac.in', department: 'CSE', year: '2nd Year', status: 'active' },
];

// --- Mock Faculty List ---
export const mockFacultyList = [
  { id: 'FAC-2024-001', name: 'Dr. Priya Sharma', email: 'priya.sharma@abes.ac.in', department: 'CSE', designation: 'Associate Professor', status: 'active' },
  { id: 'FAC-2024-002', name: 'Dr. Rajesh Kumar', email: 'rajesh.kumar@abes.ac.in', department: 'ECE', designation: 'Professor', status: 'active' },
  { id: 'FAC-2024-003', name: 'Dr. Anil Gupta', email: 'anil.gupta@abes.ac.in', department: 'ME', designation: 'Professor', status: 'active' },
  { id: 'FAC-2024-004', name: 'Dr. Neha Singh', email: 'neha.singh@abes.ac.in', department: 'CE', designation: 'Assistant Professor', status: 'active' },
  { id: 'FAC-2024-005', name: 'Dr. Vikram Patel', email: 'vikram.patel@abes.ac.in', department: 'EE', designation: 'Associate Professor', status: 'active' },
  { id: 'FAC-2024-006', name: 'Dr. Sanjay Verma', email: 'sanjay.verma@abes.ac.in', department: 'IT', designation: 'Professor', status: 'active' },
];

// --- Mock Complaints ---
const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();
const hoursAgo = (h) => new Date(now.getTime() - h * 3600000).toISOString();

export const mockComplaints = [
  {
    id: 'CMP-2024-00001',
    title: 'Wi-Fi not working in Block C hostel rooms',
    category: 'internet',
    department: 'IT',
    departmentId: 'it',
    description: 'The Wi-Fi in Block C, Floor 3 has been down for the past 3 days. Students are unable to access online resources for their assignments and projects. Multiple complaints have been raised verbally but no action has been taken. This is severely affecting our academic work, especially since semester exams are approaching.',
    priority: 'high',
    status: 'in_progress',
    location: 'Block C, Floor 3, Hostel',
    isAnonymous: false,
    createdBy: 'STU-2024-001',
    createdByName: 'Arjun Mehta',
    assignedTo: 'FAC-2024-006',
    assignedToName: 'Dr. Sanjay Verma',
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(5),
    expectedResolution: daysAgo(-2),
    attachments: [
      { name: 'wifi_error_screenshot.png', size: 245000, type: 'image/png' },
    ],
    timeline: [
      { status: 'submitted', date: daysAgo(3), note: 'Complaint submitted by student', by: 'Arjun Mehta' },
      { status: 'in_review', date: daysAgo(2.5), note: 'Complaint received and under review', by: 'System' },
      { status: 'assigned', date: daysAgo(2), note: 'Assigned to IT Department', by: 'Admin' },
      { status: 'in_progress', date: daysAgo(1), note: 'Network team investigating the router issue', by: 'Dr. Sanjay Verma' },
    ],
    comments: [
      { id: 'c1', user: 'Dr. Sanjay Verma', role: 'faculty', text: 'We have identified a faulty router on Floor 3. Replacement has been ordered.', date: hoursAgo(12) },
      { id: 'c2', user: 'Arjun Mehta', role: 'student', text: 'Thank you for the update. When can we expect the replacement?', date: hoursAgo(8) },
      { id: 'c3', user: 'Dr. Sanjay Verma', role: 'faculty', text: 'The router should arrive by tomorrow. We will install it immediately.', date: hoursAgo(5) },
    ],
  },
  {
    id: 'CMP-2024-00002',
    title: 'Water leakage in 2nd floor washroom',
    category: 'water',
    department: 'Administration',
    departmentId: 'admin_dept',
    description: 'There is a continuous water leakage from the ceiling in the boys washroom on the 2nd floor of the main academic building. The floor is always wet and slippery, creating a safety hazard for students. The leakage seems to be coming from the water tank above.',
    priority: 'urgent',
    status: 'assigned',
    location: 'Main Building, 2nd Floor, Boys Washroom',
    isAnonymous: false,
    createdBy: 'STU-2024-003',
    createdByName: 'Rahul Verma',
    assignedTo: null,
    assignedToName: null,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(3),
    expectedResolution: daysAgo(-1),
    attachments: [
      { name: 'leakage_photo1.jpg', size: 512000, type: 'image/jpeg' },
      { name: 'leakage_photo2.jpg', size: 480000, type: 'image/jpeg' },
    ],
    timeline: [
      { status: 'submitted', date: daysAgo(1), note: 'Complaint submitted by student', by: 'Rahul Verma' },
      { status: 'in_review', date: hoursAgo(20), note: 'Complaint under review', by: 'System' },
      { status: 'assigned', date: hoursAgo(3), note: 'Assigned to maintenance team', by: 'Admin' },
    ],
    comments: [],
  },
  {
    id: 'CMP-2024-00003',
    title: 'Faulty projector in Room 301',
    category: 'classroom',
    department: 'CSE',
    departmentId: 'cse',
    description: 'The projector in Room 301 has been displaying distorted colors for the past week. The red channel seems to be malfunctioning, making it difficult to read presentations and code displayed on the screen during lectures.',
    priority: 'medium',
    status: 'resolved',
    location: 'Room 301, Academic Block A',
    isAnonymous: false,
    createdBy: 'STU-2024-004',
    createdByName: 'Sneha Agarwal',
    assignedTo: 'FAC-2024-001',
    assignedToName: 'Dr. Priya Sharma',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
    expectedResolution: daysAgo(0),
    attachments: [],
    timeline: [
      { status: 'submitted', date: daysAgo(7), note: 'Complaint submitted', by: 'Sneha Agarwal' },
      { status: 'assigned', date: daysAgo(6), note: 'Assigned to CSE department', by: 'Admin' },
      { status: 'in_progress', date: daysAgo(4), note: 'Technician dispatched for repair', by: 'Dr. Priya Sharma' },
      { status: 'resolved', date: daysAgo(2), note: 'Projector lamp replaced and calibrated', by: 'Dr. Priya Sharma' },
    ],
    comments: [
      { id: 'c4', user: 'Dr. Priya Sharma', role: 'faculty', text: 'The projector has been repaired. Please verify and confirm.', date: daysAgo(2) },
      { id: 'c5', user: 'Sneha Agarwal', role: 'student', text: 'Confirmed. The projector is working perfectly now. Thank you!', date: daysAgo(1.5) },
    ],
  },
  {
    id: 'CMP-2024-00004',
    title: 'Canteen food quality has deteriorated significantly',
    category: 'canteen',
    department: 'Administration',
    departmentId: 'admin_dept',
    description: 'Over the past month, the food quality in the main canteen has gone down significantly. The dal is often watery, rotis are stale, and the hygiene standards are not being maintained. Multiple students have fallen sick after eating from the canteen.',
    priority: 'high',
    status: 'in_review',
    location: 'Main Canteen',
    isAnonymous: true,
    createdBy: 'anonymous',
    createdByName: 'Anonymous',
    assignedTo: null,
    assignedToName: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    expectedResolution: daysAgo(-5),
    attachments: [
      { name: 'canteen_complaint.pdf', size: 128000, type: 'application/pdf' },
    ],
    timeline: [
      { status: 'submitted', date: daysAgo(2), note: 'Anonymous complaint submitted', by: 'Anonymous' },
      { status: 'in_review', date: daysAgo(1), note: 'Under review by administration', by: 'Admin' },
    ],
    comments: [],
  },
  {
    id: 'CMP-2024-00005',
    title: 'Broken AC unit in Computer Lab 2',
    category: 'infrastructure',
    department: 'CSE',
    departmentId: 'cse',
    description: 'The air conditioning unit in Computer Lab 2 is not functioning. With 60+ students in the lab during peak hours, the temperature becomes unbearable, affecting concentration and making it difficult to conduct practical sessions.',
    priority: 'high',
    status: 'submitted',
    location: 'Computer Lab 2, Block B',
    isAnonymous: false,
    createdBy: 'STU-2024-001',
    createdByName: 'Arjun Mehta',
    assignedTo: null,
    assignedToName: null,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
    expectedResolution: daysAgo(-3),
    attachments: [],
    timeline: [
      { status: 'submitted', date: hoursAgo(6), note: 'Complaint submitted', by: 'Arjun Mehta' },
    ],
    comments: [],
  },
  {
    id: 'CMP-2024-00006',
    title: 'Library books not returned by previous batch',
    category: 'library',
    department: 'Administration',
    departmentId: 'admin_dept',
    description: 'Several important reference books for Data Structures and Algorithms are not available in the library because the previous batch students have not returned them. The library staff says they cannot issue new copies until the old ones are returned.',
    priority: 'low',
    status: 'resolved',
    location: 'Central Library',
    isAnonymous: false,
    createdBy: 'STU-2024-009',
    createdByName: 'Rohan Patel',
    assignedTo: 'FAC-2024-001',
    assignedToName: 'Dr. Priya Sharma',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(5),
    expectedResolution: daysAgo(2),
    attachments: [],
    timeline: [
      { status: 'submitted', date: daysAgo(14), note: 'Complaint submitted', by: 'Rohan Patel' },
      { status: 'assigned', date: daysAgo(12), note: 'Assigned to library coordinator', by: 'Admin' },
      { status: 'in_progress', date: daysAgo(10), note: 'Contacting previous batch students', by: 'Dr. Priya Sharma' },
      { status: 'resolved', date: daysAgo(5), note: 'Books recovered and new copies ordered', by: 'Dr. Priya Sharma' },
    ],
    comments: [
      { id: 'c6', user: 'Dr. Priya Sharma', role: 'faculty', text: 'We have recovered 8 out of 12 books and ordered replacements for the rest.', date: daysAgo(5) },
    ],
  },
  {
    id: 'CMP-2024-00007',
    title: 'Electricity fluctuation in Hostel Block A',
    category: 'electricity',
    department: 'Hostel Management',
    departmentId: 'hostel',
    description: 'There are frequent power fluctuations in Block A of the hostel, especially during evening hours (6 PM - 10 PM). This has damaged two laptop chargers and a study lamp. The voltage stabilizer in the common room is also not working.',
    priority: 'urgent',
    status: 'in_progress',
    location: 'Hostel Block A',
    isAnonymous: false,
    createdBy: 'STU-2024-005',
    createdByName: 'Vikas Yadav',
    assignedTo: 'FAC-2024-005',
    assignedToName: 'Dr. Vikram Patel',
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(8),
    expectedResolution: daysAgo(-1),
    attachments: [
      { name: 'damaged_charger.jpg', size: 320000, type: 'image/jpeg' },
    ],
    timeline: [
      { status: 'submitted', date: daysAgo(4), note: 'Complaint submitted', by: 'Vikas Yadav' },
      { status: 'assigned', date: daysAgo(3), note: 'Assigned to electrical dept', by: 'Admin' },
      { status: 'in_progress', date: daysAgo(2), note: 'Electrician inspecting wiring', by: 'Dr. Vikram Patel' },
    ],
    comments: [
      { id: 'c7', user: 'Dr. Vikram Patel', role: 'faculty', text: 'Found faulty wiring in the main distribution panel. Repair work scheduled for tomorrow.', date: hoursAgo(8) },
    ],
  },
  {
    id: 'CMP-2024-00008',
    title: 'Transport bus frequently late on Route 5',
    category: 'transport',
    department: 'Administration',
    departmentId: 'admin_dept',
    description: 'The college bus on Route 5 (Noida Sector 62 - ABES) has been arriving 30-45 minutes late for the past 2 weeks. Students are missing their first lectures regularly. The bus driver seems to take a longer route than necessary.',
    priority: 'medium',
    status: 'rejected',
    location: 'Route 5 - Noida Sector 62',
    isAnonymous: false,
    createdBy: 'STU-2024-002',
    createdByName: 'Priya Gupta',
    assignedTo: null,
    assignedToName: null,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
    expectedResolution: daysAgo(3),
    attachments: [],
    timeline: [
      { status: 'submitted', date: daysAgo(10), note: 'Complaint submitted', by: 'Priya Gupta' },
      { status: 'in_review', date: daysAgo(9), note: 'Under review', by: 'Admin' },
      { status: 'rejected', date: daysAgo(8), note: 'Route timings adjusted per traffic conditions. No further action required.', by: 'Admin' },
    ],
    comments: [
      { id: 'c8', user: 'Mr. Ravi Tiwari', role: 'admin', text: 'After investigation, the delay is due to road construction on Sector 62. The route has been modified accordingly. The bus timing has been adjusted to 7:15 AM.', date: daysAgo(8) },
    ],
  },
  {
    id: 'CMP-2024-00009',
    title: 'Examination hall seating arrangement issue',
    category: 'examination',
    department: 'Administration',
    departmentId: 'admin_dept',
    description: 'During the mid-term examinations, the seating arrangement was very cramped in Hall B. Desks were placed too close together, making it uncomfortable to write and raising concerns about cheating. Request better seating arrangement for end-term exams.',
    priority: 'medium',
    status: 'closed',
    location: 'Examination Hall B',
    isAnonymous: true,
    createdBy: 'anonymous',
    createdByName: 'Anonymous',
    assignedTo: null,
    assignedToName: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(20),
    expectedResolution: daysAgo(15),
    attachments: [],
    timeline: [
      { status: 'submitted', date: daysAgo(30), note: 'Anonymous complaint submitted', by: 'Anonymous' },
      { status: 'in_review', date: daysAgo(28), note: 'Under review', by: 'Admin' },
      { status: 'resolved', date: daysAgo(22), note: 'Seating plan revised for end-term exams', by: 'Admin' },
      { status: 'closed', date: daysAgo(20), note: 'Complaint closed after resolution', by: 'System' },
    ],
    comments: [],
  },
  {
    id: 'CMP-2024-00010',
    title: 'Security guard misbehavior at main gate',
    category: 'security',
    department: 'Administration',
    departmentId: 'admin_dept',
    description: 'The security guard posted at the main gate during the morning shift has been repeatedly rude to students while checking ID cards. He shouted at a female student yesterday causing distress. This behavior is unacceptable and needs immediate attention.',
    priority: 'urgent',
    status: 'in_progress',
    location: 'Main Gate',
    isAnonymous: true,
    createdBy: 'anonymous',
    createdByName: 'Anonymous',
    assignedTo: 'FAC-2024-003',
    assignedToName: 'Dr. Anil Gupta',
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(2),
    expectedResolution: daysAgo(-1),
    attachments: [],
    timeline: [
      { status: 'submitted', date: daysAgo(1), note: 'Anonymous complaint submitted', by: 'Anonymous' },
      { status: 'assigned', date: hoursAgo(18), note: 'Assigned to security committee', by: 'Admin' },
      { status: 'in_progress', date: hoursAgo(2), note: 'Investigation initiated', by: 'Dr. Anil Gupta' },
    ],
    comments: [],
  },
  {
    id: 'CMP-2024-00011',
    title: 'Washroom cleaning not being done regularly',
    category: 'washroom',
    department: 'Administration',
    departmentId: 'admin_dept',
    description: 'The washrooms on the 3rd floor of Academic Block B have not been cleaned for the past 3 days. There is a bad odor and the floor is dirty. The soap dispensers are empty and there is no water in some taps.',
    priority: 'high',
    status: 'submitted',
    location: 'Academic Block B, 3rd Floor',
    isAnonymous: false,
    createdBy: 'STU-2024-007',
    createdByName: 'Karan Sharma',
    assignedTo: null,
    assignedToName: null,
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
    expectedResolution: daysAgo(-1),
    attachments: [],
    timeline: [
      { status: 'submitted', date: hoursAgo(4), note: 'Complaint submitted', by: 'Karan Sharma' },
    ],
    comments: [],
  },
  {
    id: 'CMP-2024-00012',
    title: 'Request for additional study room access hours',
    category: 'library',
    department: 'Administration',
    departmentId: 'admin_dept',
    description: 'With exams approaching, students need extended access to study rooms in the library. Currently the library closes at 6 PM, but students would benefit from extended hours until 10 PM during exam season.',
    priority: 'low',
    status: 'in_review',
    location: 'Central Library',
    isAnonymous: false,
    createdBy: 'STU-2024-001',
    createdByName: 'Arjun Mehta',
    assignedTo: null,
    assignedToName: null,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
    expectedResolution: daysAgo(-7),
    attachments: [
      { name: 'petition_signed.pdf', size: 890000, type: 'application/pdf' },
    ],
    timeline: [
      { status: 'submitted', date: daysAgo(5), note: 'Complaint submitted with signed petition', by: 'Arjun Mehta' },
      { status: 'in_review', date: daysAgo(3), note: 'Under review by library committee', by: 'Admin' },
    ],
    comments: [
      { id: 'c9', user: 'Mr. Ravi Tiwari', role: 'admin', text: 'Your request has been forwarded to the library committee. We will update you within a week.', date: daysAgo(3) },
    ],
  },
];

// --- Mock Notifications ---
export const mockNotifications = [
  {
    id: 'n1',
    title: 'Complaint Status Updated',
    message: 'Your complaint "Wi-Fi not working in Block C" has been assigned to Dr. Sanjay Verma.',
    type: 'status_update',
    read: false,
    createdAt: hoursAgo(2),
    complaintId: 'CMP-2024-00001',
  },
  {
    id: 'n2',
    title: 'New Comment on Your Complaint',
    message: 'Dr. Sanjay Verma commented: "The router should arrive by tomorrow."',
    type: 'comment',
    read: false,
    createdAt: hoursAgo(5),
    complaintId: 'CMP-2024-00001',
  },
  {
    id: 'n3',
    title: 'Complaint Resolved',
    message: 'Your complaint "Faulty projector in Room 301" has been resolved.',
    type: 'resolved',
    read: true,
    createdAt: daysAgo(2),
    complaintId: 'CMP-2024-00003',
  },
  {
    id: 'n4',
    title: 'New Announcement',
    message: 'Mid-semester exam schedule has been published. Check the notice board.',
    type: 'announcement',
    read: true,
    createdAt: daysAgo(3),
    complaintId: null,
  },
  {
    id: 'n5',
    title: 'Complaint Rejected',
    message: 'Complaint "Transport bus frequently late" has been reviewed and closed with remarks.',
    type: 'rejected',
    read: true,
    createdAt: daysAgo(8),
    complaintId: 'CMP-2024-00008',
  },
  {
    id: 'n6',
    title: 'System Maintenance',
    message: 'The portal will be under maintenance on Sunday from 2 AM to 6 AM.',
    type: 'system',
    read: false,
    createdAt: hoursAgo(1),
    complaintId: null,
  },
];

// --- Mock Announcements ---
export const mockAnnouncements = [
  {
    id: 'a1',
    title: 'End Semester Examination Schedule Released',
    content: 'The end semester examination for all branches will commence from December 15, 2024. Students are advised to check the detailed schedule on the university portal and prepare accordingly.',
    author: 'Examination Cell',
    isPinned: true,
    createdAt: daysAgo(2),
    category: 'examination',
  },
  {
    id: 'a2',
    title: 'Annual Tech Fest "TechNova 2024" Registration Open',
    content: 'Registration for TechNova 2024 is now open. The fest will be held from November 15-17 with events in coding, robotics, AI/ML, and more. Early bird registration closes on October 30.',
    author: 'Student Council',
    isPinned: true,
    createdAt: daysAgo(5),
    category: 'event',
  },
  {
    id: 'a3',
    title: 'Library Extended Hours During Exam Season',
    content: 'The central library will remain open until 10 PM from December 1 to December 30 to support students during exam preparation.',
    author: 'Library Committee',
    isPinned: false,
    createdAt: daysAgo(7),
    category: 'general',
  },
  {
    id: 'a4',
    title: 'Campus Placement Drive - Infosys',
    content: 'Infosys will be conducting a campus placement drive on November 5, 2024. Eligible students from CSE, IT, and ECE branches with CGPA > 7.0 can register.',
    author: 'Training & Placement Cell',
    isPinned: false,
    createdAt: daysAgo(10),
    category: 'placement',
  },
];

// --- Mock Events ---
export const mockEvents = [
  { id: 'e1', title: 'Guest Lecture - AI in Healthcare', date: daysAgo(-3), location: 'Auditorium', department: 'CSE' },
  { id: 'e2', title: 'Workshop on IoT', date: daysAgo(-5), location: 'Lab 4', department: 'ECE' },
  { id: 'e3', title: 'Sports Day', date: daysAgo(-10), location: 'Sports Ground', department: 'All' },
  { id: 'e4', title: 'Hackathon 2024', date: daysAgo(-15), location: 'CSE Block', department: 'CSE' },
];

// --- Chart Data for Admin Dashboard ---
export const monthlyComplaintData = [
  { month: 'Jan', complaints: 45, resolved: 38 },
  { month: 'Feb', complaints: 52, resolved: 44 },
  { month: 'Mar', complaints: 38, resolved: 35 },
  { month: 'Apr', complaints: 65, resolved: 50 },
  { month: 'May', complaints: 48, resolved: 42 },
  { month: 'Jun', complaints: 30, resolved: 28 },
  { month: 'Jul', complaints: 55, resolved: 45 },
  { month: 'Aug', complaints: 70, resolved: 55 },
  { month: 'Sep', complaints: 60, resolved: 52 },
  { month: 'Oct', complaints: 75, resolved: 60 },
  { month: 'Nov', complaints: 58, resolved: 48 },
  { month: 'Dec', complaints: 42, resolved: 40 },
];

export const departmentComplaintData = [
  { department: 'CSE', complaints: 85, resolved: 70 },
  { department: 'ECE', complaints: 45, resolved: 38 },
  { department: 'ME', complaints: 32, resolved: 28 },
  { department: 'Admin', complaints: 120, resolved: 95 },
  { department: 'IT', complaints: 65, resolved: 55 },
  { department: 'EE', complaints: 28, resolved: 25 },
  { department: 'Hostel', complaints: 95, resolved: 72 },
];

export const categoryPieData = [
  { name: 'Infrastructure', value: 120, color: '#1e3a8a' },
  { name: 'Internet', value: 85, color: '#2563eb' },
  { name: 'Hostel', value: 95, color: '#7c3aed' },
  { name: 'Canteen', value: 60, color: '#f59e0b' },
  { name: 'Transport', value: 45, color: '#10b981' },
  { name: 'Library', value: 35, color: '#ef4444' },
  { name: 'Security', value: 30, color: '#0891b2' },
  { name: 'Other', value: 68, color: '#64748b' },
];

// Heatmap data (24 hours × 7 days)
export const heatmapData = (() => {
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const data = [];
  days.forEach((day, di) => {
    for (let hour = 0; hour < 24; hour++) {
      // More complaints during working hours
      let value = Math.floor(Math.random() * 3);
      if (hour >= 8 && hour <= 18) value = Math.floor(Math.random() * 10) + 2;
      if (hour >= 10 && hour <= 14) value = Math.floor(Math.random() * 15) + 5;
      if (di >= 5) value = Math.floor(value * 0.3); // Less on weekends
      data.push({ day, hour, value });
    }
  });
  return data;
})();

// Admin stats
export const adminStats = {
  totalStudents: 2450,
  totalFaculty: 186,
  totalComplaints: 638,
  activeComplaints: 124,
  pendingComplaints: 47,
  resolvedComplaints: 489,
  rejectedComplaints: 25,
  avgResolutionTime: '3.2 days',
  satisfactionRate: 87,
  thisMonthComplaints: 58,
  lastMonthComplaints: 75,
  growthRate: -22.7,
};

// Student stats (for the logged-in student)
export const studentStats = {
  total: 5,
  pending: 1,
  inProgress: 1,
  resolved: 2,
  rejected: 1,
};
